# Use container-based infrastructure
sudo: required
dist: trusty

services:
  - docker

language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8  # sbt +compile fails on jdk11 (xenial's default)

jobs:
  include:
    - stage: "Mleap tests"
      name: "Scala Tests"
      script:
        - travis/travis.sh

    - name: "Python black tests"
        language: python
        python: 3.6
        install:
          - pip install "virtualenv<20.0.0" tox  # Bug https://github.com/pypa/virtualenv/issues/1551
        script:
          - make black_test

    - name: "Python 3.6 tests"
      language: python
      python: 3.6
      script:
        - make py36_test

    - name: "Python 3.7 tests"
      language: python  # This can't be java and python at the same time
      python: 3.7
      env:
        # Required when not setting 'language: java' to force the correct jdk8
        - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
        - JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"
      dist: xenial  # Travis won't install py37 on trusty
      install:
        - pip install "virtualenv<20.0.0" tox  # Bug https://github.com/pypa/virtualenv/issues/1551
      script:
        - make py37_test

notifications:
  on_success: change
  on_failure: always
  urls:
    - https://webhooks.gitter.im/e/65cd239c75c243ce635e
  slack:
    rooms:
      - secure: "RLxhNQarrr8WNtJRSx855EJX6w9XsyvzfhJGHrJYcNs5hNZfnCcWJaGRExqSHjd3UKpyZOgOAa0+5IrUl4Pbug7Dzq+Kk5nIOxdDILfcL8giVXV2bMfeGADKyiDdkwyeud4eb0Oc7uVhFfmelW8d3EFPWio4yXUaVGZl0cNpCfx9iF1r0vLwRb7U5fiicuvpz8tNZkw6Vp8lrW0+teeXWpzVopxh4gTZxULlaVvp28OIJ09dS2k02baL6g3L4G4z9IxW4adEdH6DpAbw0JgyAFjZE1BXoEQuoZvHjoYstwy62f+maB8c2xNEB9bzobUruc0JHLKly0AdOqtKL25OCeSD3qBVWZKK/TOSQ4phY+iapI1JB5JCoZj/z/k5YogxdRGjFGyUhupuR8+kqZuAUAegD9N5wOLgwei5GTD2oim90ZixeS1Do7GvqhRiyaRHSL0CKRyJXV/iiDr1a8zV5tW8uREZX29Jq5DObxCTLDrWGjqijNWC06lOV0dhvF83qov9A1c+yulrS28qP7Hn7MXQWETShvlw4YxBCDGQLNJ3BMwA9nOx9O0ZI+0KCNVXPu6n8ZVbahJg0LoYZ2ftGFiwxq1/svlhInUN57MXkgI6iDf7NojAL7urGwN3YWbxuJemnASjPtigkN2yboAsBG/aSjOiYNeIVfna//XrFeI="
      - secure: "Afbm/moiSBB7Kn9J9mX4h+ss4cju6WvOBqup0WdkNCUPWKPFs3XRkt8sDZzAyhn7Fu2w4+NclGI/QHhMo8fC+eZG9fhbpPyVoZv1o9e/43qALOB4nXnZGZeGQLdDTFLcx6ylNEK63cQrro5xY7jCwfPYhuakGr9SWkabX6mKqZWThNyH2HPbKQZX540rRwPOxIVgnkhHleCC1vosfgD1brNBt/100cXZXBVjP7GXSJbBDPuKf+cG+bUNET0xxoBK9GurZl8UDhIoo7jfoAj1tY9l0cgzMjxdSO5Yn5Z73DMT3XfiOlT8Hjp+fC37pvssKsfSg72KgTidva71CGwCoJ/B4ly2BtiXNuazzd1vAyCirbJKT8YQwPGihElkaANtMcpWjtnn0v3nTfMvooMT+HRip4kBtfE7Rl+JeVKET0Hhi0Er16eGoCL/XzVuJB7Cfh6B6UJTqHSv3PqeCVP3PQm+qp07VT6KjmMXa2rbMuh5ybs6hQIgZLVc3BeAjGWCZndRxcwgNpG+UvT7Fz87fWOBrN6xZVctXylWatjizf1IXEwBz25X05gMBnafeC3whhX/8jSR3NikwVgY4UQb4mgfSPqXgCeaVQ8VHeLpTM7swVI3q1Vcmms/v7YdPEFGDFLcyYo24GojgBaBZCl7WAk4QxxGrAANqcMpOWXhALo="
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
